{% set name = "jaraco.classes" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dcc2c4a8ca4b344cdbf2e1be7124a5c4f192574cdbb453b62350ae8240a2caf5

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  
requirements:
  host:
    - python
    - pip
    - setuptools_scm >=1.15.0
  run:
    - python
    - six

test:
  imports:
    - jaraco
    - jaraco.classes

about:
  home: https://github.com/jaraco/jaraco.classes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'jaraco.classes'
  dev_url: https://github.com/jaraco/jaraco.classes

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
