# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "gA+/QtEIuXPf+tr72eFzQ1OOgimXlg0MN3wkv/YXGDbpFmfX4u3tELF39aZ41FDi0UdCfHXmN3+T2hJXcBFO1Qg/sOhtrfZuKY3yddI1U6UfaoTdLygZw8QGlRjnRSGVHdEsUZ9rN/LS1AFNQIKPWbeQexo7kNR5uCjwTQppczOx3W0wJDXuqVUCO/ZOcfmzZ6+GoByStOzv76YL1Yv9dCMEhBWwDhCPn9Xn01VwClNEgBVv687Yi4aK01MOs5rXl3iTN45PsJgyy0SJg33vvXpNwJuEfJzrKxG9erh/XlAAxcdjDBkswsDiECy+kZZTZr1IK7ldu4fLbjZIDg3yuHzNcTnkjudj5o48WepnELF3LNnq7CjNWjyDxvy7xoQcw+UCDkbqUck+RqROB3i5aPGXmItBuf9VBr3Gi88LgsHW27KmXYDEO7pAlM8ZLlBI1D2SH7DG7imyFPk9JnO+E8hPvmpoN5zl9lKpKZpW8Qee3i+6s6SUDt1XEgMxBebKD0lx1ainvncTeeb20gM6ImMsk0960Q814ZiWxPUcI/i8At9dfp6Si84iUYp+sHiGmNobAd6OuaA/XxiyBOlgiI3MPP7tvU9gW4pEHpv1cGsH6Uwo/19W/GF77M0K6PG+wPMWFkz/XPx06hKmjJNY6N9Jhzg/fGyu68ASq4fuk2s="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
