travis:
  secure:
    BINSTAR_TOKEN: gA+/QtEIuXPf+tr72eFzQ1OOgimXlg0MN3wkv/YXGDbpFmfX4u3tELF39aZ41FDi0UdCfHXmN3+T2hJXcBFO1Qg/sOhtrfZuKY3yddI1U6UfaoTdLygZw8QGlRjnRSGVHdEsUZ9rN/LS1AFNQIKPWbeQexo7kNR5uCjwTQppczOx3W0wJDXuqVUCO/ZOcfmzZ6+GoByStOzv76YL1Yv9dCMEhBWwDhCPn9Xn01VwClNEgBVv687Yi4aK01MOs5rXl3iTN45PsJgyy0SJg33vvXpNwJuEfJzrKxG9erh/XlAAxcdjDBkswsDiECy+kZZTZr1IK7ldu4fLbjZIDg3yuHzNcTnkjudj5o48WepnELF3LNnq7CjNWjyDxvy7xoQcw+UCDkbqUck+RqROB3i5aPGXmItBuf9VBr3Gi88LgsHW27KmXYDEO7pAlM8ZLlBI1D2SH7DG7imyFPk9JnO+E8hPvmpoN5zl9lKpKZpW8Qee3i+6s6SUDt1XEgMxBebKD0lx1ainvncTeeb20gM6ImMsk0960Q814ZiWxPUcI/i8At9dfp6Si84iUYp+sHiGmNobAd6OuaA/XxiyBOlgiI3MPP7tvU9gW4pEHpv1cGsH6Uwo/19W/GF77M0K6PG+wPMWFkz/XPx06hKmjJNY6N9Jhzg/fGyu68ASq4fuk2s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
