travis:
  secure:
    BINSTAR_TOKEN: j6VGI2pLnXcVia4DYzc8bphsj8VmMyimee5k1zWswZozM2S2xC9pb1//08TEKLSFvrHjpJKkd5xiRc9jZACdF4HPJGGXpldAUy2EIM7dP4bBwNt7CY9m3tOZxvo6z3R0Vu5TCkz3JS8EcbTzw/D0fCu29OFIGHrCOA1X8MNc9tV1D/XELPF7PnqTjEkHjWxWnMIlFNG6Piz/+gyXa81phHW48w88SDCRhjsfYa7Dl2hSk7iC8gdBjMeiZr0Fb7Xpk0+AGi/tfcdgsVl/d6azKVeGHPSwbDWlq+0SSYvgNjNiJHUphP+033cT2/Tk0q8IxXLrisiUiah3pOBA2SiBWYUDL1cov4XzknBJfJ+epIhTJMUM2InW+GC3kwLVS0WzkalWH8F69/Y6J9kj4quqkLwWs3pd7Tn0wAstQ2wNKzhGQP2F6TOrf7+MVb1JHugsn8sHJtOfAiDVFvfvuRdV9awdBD7AH6yKeZe+0/MXCj4qN+kcKEiSGc4Uk+Lv62pCZ9REUU2TtZc4OrEg/rHa7np7hX5TeVUAUc0oR4V99s7dJl5/mysPP5TurMYVuoRBfTuZ9DDTJ61mQxGuzItHjKuRb1qIHWzahl3B7GhMlif+YcQxtLhyXH73Lns3sSsVEQrszvqRSJqzpas7RmdK4wZk2txOpYb4xhhjGE0eSeM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
